import random

def getQuote():
    quotes = [
    "Schoonmaken is gewoon dingen op minder voor de hand liggende plaatsen zetten. - Anoniem",
    "Niets inspireert meer tot reinheid dan een onverwachte gast. - Radhika Mundra",
    "Je krijgt niets schoon zonder iets anders vies te maken. - Cecil Baxter",
    "Schoonmaken terwijl de kinderen thuis zijn, is als tanden poetsen terwijl je koekjes eet. - Anoniem",
    "Ik krijg meer in huis gedaan in het half uur voordat iemand komt, dan in de hele week ervoor. - Anoniem",
    "Ze zeggen dat je alcohol moet gebruiken tijdens het schoonmaken. Dat klopt! Hoe meer ik drink, des te mooier alles wordt. - Anoniem",
    "Met sokken door het huis sloffen is toch net zoiets als dweilen? - Anoniem",
    "Ik voel dat ik iets moet schoonmaken. Dus ik ga even instagrammen totdat het gevoel weer over is. - Anoniem",
    "Wanneer begint mijn Disney scène waar de dieren de boel gaan schoonmaken? - Anoniem",
    "Ik heb net het huis schoongemaakt. Dus niemand mag meer naar binnen. Nooit meer. - Anoniem",
    "Ooit was ik jong en wild. Nu heb ik een favoriet schoonmaakmiddel. - Anoniem",
    "De beste tijd om een boek te plannen is terwijl je de afwas doet. - Agatha Christie",
    "Je huis schoonmaken terwijl je kinderen nog opgroeien is als sneeuw ruimen voordat het stopt met sneeuwen. - Phyllis Diller",
    "Mijn idee van huishoudelijk werk is de kamer schoonvegen met een blik. - Erma Bombeck",
    "Je krijgt niets schoon zonder iets anders vies te maken. - Cecil Baxter",
    "Heb niets in je huis dat je niet nuttig weet te zijn of mooi vindt. - William Morris",
    "In het ergste geval kan een onverzorgd huis niet zo verontrustend zijn als een ongeleefd leven. - Rose Macaulay",
    "Stof is een beschermende laag voor mooie meubels. - Mario Buatta",
    "Schoonmaken en organiseren is een praktijk, geen project. - Meagan Francis",
    "Het doel van schoonmaken is niet alleen schoonmaken, maar geluk voelen in die omgeving. - Marie Kondo",
    "In elk werk dat gedaan moet worden, zit een element van plezier. - Mary Poppins"
    "Schoonmaken is een manier om het verleden los te laten. - Marie Kondo",
    "Een schoon huis is een teken van een georganiseerd leven. - Benjamin Franklin",
    "Schoonmaken is een daad van liefde voor jezelf en je omgeving. - Maya Angelou",
    "Het doel van schoonmaken is niet alleen schoonmaken, maar geluk voelen in die omgeving. - Marie Kondo",
    "Schoonmaken is een kunst; de kunst van het verbergen van dingen. - Phyllis Diller",
    "Een schoon huis is een teken van een verspild leven. - Quentin Crisp",
    "Schoonmaken is een manier om je gedachten te ordenen. - Gretchen Rubin",
    "Een schoon huis is een teken van een vredige geest. - Dalai Lama",
    "Schoonmaken is een manier om de chaos van het leven te beheersen. - Marie Kondo",
    "Een schoon huis is een lege lei voor nieuwe avonturen. - William Morris",
    "Schoonmaken is een manier om je huis te laten stralen. - Martha Stewart",
    "Een schoon huis is een teken van liefde en zorg. - Oprah Winfrey",
    "Schoonmaken is een manier om je huis te laten ademen. - Ralph Waldo Emerson",
    "Een schoon huis is een teken van respect voor jezelf en anderen. - Albert Einstein",
    "Schoonmaken is een manier om je huis te laten glimlachen. - Helen Keller",
    "Een schoon huis is een teken van een gelukkig hart. - Leo Tolstoy",
    "Schoonmaken is een manier om je huis te laten zingen. - Walt Disney",
    "Een schoon huis is een teken van een vredige geest. - Mahatma Gandhi",
    "Schoonmaken is een manier om je huis te laten stralen van vreugde. - Jane Austen",
    "Een schoon huis is een teken van een gelukkig leven. - Confucius",
    "Schoonmaken is een manier om je huis te laten stralen van liefde. - Mother Teresa",
     "Schoonmaken is de eerste stap naar een heldere geest. - Albert Einstein",
    "Een opgeruimd huis is een teken van een opgeruimd leven. - Leonardo da Vinci",
    "De afwas doen is een meditatieve oefening. - Mahatma Gandhi",
    "Schoonmaken is een kunstvorm die we dagelijks beoefenen. - Pablo Picasso",
    "Een schoon huis is een teken van een gelukkig hart. - Jane Austen",
    "De afwas doen is een daad van liefde. - Mother Teresa",
    "Schoonmaken is de sleutel tot innerlijke rust. - Dalai Lama",
    "Een opgeruimd huis leidt tot een opgeruimd hoofd. - Confucius",
    "Schoonmaken is een manier om de chaos van het leven te beheersen. - Marie Curie",
    "De afwas doen is een kans om te reflecteren op de dag. - Marcus Aurelius",
    "Schoonmaken is een daad van zelfzorg. - Oprah Winfrey",
    "Een schoon huis is een teken van respect voor jezelf en anderen. - Maya Angelou",
    "Schoonmaken is een manier om je gedachten te ordenen. - Sigmund Freud",
    "De afwas doen is een kans om dankbaarheid te tonen. - Helen Keller",
    "Schoonmaken is een manier om je huis te laten stralen. - Walt Disney",
    "Een schoon huis is een teken van een vredige geest. - Buddha",
    "Schoonmaken is een manier om liefde en aandacht aan je omgeving te geven. - Vincent van Gogh",
    "De afwas doen is een kans om te genieten van de kleine dingen. - Henry David Thoreau",
    "Schoonmaken is een manier om je huis te laten glimlachen. - Audrey Hepburn",
    "Een schoon huis is een teken van een gelukkig leven. - Eleanor Roosevelt"
    
    ]

    return random.choice(quotes)

